/** Playwright / smoke용 stable selectors (mock UI). */
export const P2P_TEST_IDS = Object.freeze({
  tradeList: "p2p-trade-list",
  progressOrders: "p2p-progress-orders",
  timeline: "p2p-trade-timeline",
  escrowPanel: "p2p-escrow-panel",
  matrixBadge: "p2p-matrix-badge",
  matrixStrip: "p2p-matrix-strip",
  flowStepper: "p2p-flow-stepper",
  adminAudit: "p2p-admin-audit",
  adminAuditKpi: "p2p-admin-audit-kpi",
  adminAuditRow: "p2p-admin-audit-row",
  adminAuditTable: "p2p-admin-audit-table",
  devDiagnostics: "p2p-dev-diagnostics",
  adminCacheState: "p2p-admin-cache-state",
  escrowLegend: "p2p-escrow-legend",
  adminAuditKpiCard: "p2p-admin-audit-kpi-card",
  validationBadge: "p2p-validation-badge",
  mockOnlyBadge: "p2p-mock-only-badge",
  adminAuditTab: "p2p-admin-audit-tab",
  uteSurfaceTab: "p2p-ute-surface-tab",
  uteSurfacePanel: "p2p-ute-surface-panel",
  devDiagnosticsCompact: "p2p-dev-diagnostics-compact",
  simpleAdminSmokeRoot: "p2p-simple-admin-smoke-root",
});
